### ISSUE TITLE
Loss of '2.1/forkjoin/README.txt'

### ISSUE THREAD

**Issue by jhsy1209021** [accellera-official/systemc#84] opened 2024-05-06 13:06 UTC
The loss of **'2.1/forkjoin/README.txt'** will cause the make return error. The problem can be fix by creating empty README.txt under '2.1/forkjoin.' Is this file accidentally missed?

SystemC Version: 3.0.0 (06ab23bc392cad78da8ab5d413fdc5d1a694dfe2)
Platform: Ubuntu20.04 (5.15.0-105-generic)
Compiler: g++ 9.4.0
Compile Flags: -std=c++17
Error Message:
```
make[1]: Entering directory 'systemc/objdir/examples'
Making all in sysc
make[2]: Entering directory 'systemc/objdir/examples/sysc'
make[2]: *** No rule to make target '2.1/forkjoin/README.txt', needed by 'all-am'.  Stop.
make[2]: Leaving directory 'systemc/objdir/examples/sysc'
make[1]: *** [Makefile:503: all-recursive] Error 1
make[1]: Leaving directory 'systemc/objdir/examples'
make: *** [Makefile:513: all-recursive] Error 1
```

**Comment by maehne** [comment] 2024-05-06 14:44
This is a duplicate of PR #82 and the internal issue https://github.com/OSCI-WG/systemc/issues/653 fixed by PR https://github.com/OSCI-WG/systemc/pull/655. The fix is already present in the main branch of this repository (commit https://github.com/accellera-official/systemc/commit/9d337e5cb9be59001c9cfac1aa5d81e7c952ec19). Please check and report if some issue remains.

**Closed** 2024-05-07 16:08 UTC

**Comment by ThomasPDye** [comment] 2024-09-21 08:51
still an issue in main release 3.0.0 furthermore no fix in main branch of this repository
